---
 - hosts: ap
   gather_facts: false
   environment: 
     http_proxy: http://192.168.0.4:3128 
     ftp_proxy: http://192.168.0.4:3128
   tasks:
   - name: create group
     group: name=tomcat state=present
   - name: create user
     user: name=tomcat group=tomcat state=present shell=/bin/false
   - name: chown -R tomcat:tomcat tomcat_root
     file: dest=/opt/tomcat/apache-tomcat-8.5.31 owner=tomcat group=tomcat recurse=yes
   - name: open tomcat port
     firewalld: port=8080/tcp permanent=true state=enabled
   - name: systemctl daemon reload
     systemd: daemon_reload=yes  
   - name: reload firewalld
     service: name=firewalld state=reloaded
   - name: start tomcat
     service: name=tomcat state=started
