---
- hosts: srv1
  gather_facts: no
  tasks:
  - include_vars: file=postgresql_pkg.yml
  - name: install postgresql repo
    yum: name=https://download.postgresql.org/pub/repos/yum/9.6/redhat/rhel-7-x86_64/pgdg-centos96-9.6-3.noarch.rpm state=present
  - name: install postgresql packages
    yum: name="{{ item }}" state=present
    with_items: "{{ postgres }}"
  - name: postgres db init
    command: /usr/pgsql-9.6/bin/initdb -D /var/lib/pgsql/9.6/data
    become: yes
    become_user: postgres
  - name: finally start the service
    service: name=postgresql-9.6 state=started
